server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.6:8761/eureka/,http://10.10.0.7:8761/eureka/,http://10.10.0.8:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info
